name: TypeScript Build and Test

on:
  push:
    branches: [main, "ci-test*"]
    paths:
      - 'stacks/**'
  pull_request_target:
    branches: [main, "ci-test*"]
    paths:
      - 'stacks/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Change to 'stacks' directory
        run: cd stacks
        
      - name: Remove node_modules
        run: rm -rf node_modules
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18" # You can specify your Node.js version here
          
      - name: Install Dependencies
        run: npm install --force
        
      - name: Run TypeScript Compiler
        run: tsc

      - name: Run Jest on Modified Files
        run: |
          # Get the list of modified files
          modified_files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})

          # Find related test files using jest --findRelatedTests
          test_files=$(npx jest --listTests --findRelatedTests $modified_files)

          # Run Jest only on modified files
          npx jest $test_files
